Repository eygraber/compose-placeholder, pull requests merged in 2024-05, with the labels that each got.

#164 Add wasmJs target
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
Labels: enhancement

#166 Fix README.md code highlighting
  README.md
Labels: chore

#180 Kotlin 2.0.0
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: dependencies

#181 Update gradle-conventions to 0.0.74
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: dependencies

#182 Use macos-latest runner for GitHub Actions
  .github/workflows/pr.yml
  .github/workflows/publish_release.yml
  .github/workflows/publish_snapshot.yml
Labels: gh-actions
